server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_log
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      jdbc-url: ${DB_URL:jdbc:postgresql://localhost:5433/db_log}
      username: ${DB_LOGIN:postgres}
      password: ${DB_PASSWORD:root}
      schema: schema_log

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  messages:
    basename: validation

  liquibase:
    change-log: classpath*:db/changelogs.xml
    enabled: ${LIQUIBASE_ENABLE:true}
    default-schema: schema_log

logging:
  file:
    name: person-service.log
  level:
    org.springframework.jdbc.core: TRACE
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 5MB

management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, loggers"